#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# @Date:  2024-0201 9:36
# @Author: sc
# @Filename: mobivis_CLI
# @Develop env: vscode

import sys

def main():
    if len(sys.argv) <= 3:
        from ..mobivision_M_cli import CustomHelp
        CustomHelp(sys.argv)
    else:
        from ..mobivision_M_cli import run_MobiVisionM
        run_MobiVisionM()

if __name__ == '__main__':
    main()